name: Update and Push

on:
  push:
    branches:
      - main

jobs:
  update_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pull and Rebase
      run: |
        git pull --rebase origin main
        # Resolve conflicts if any
        git push origin main

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
