name: Testing Secure Slicing xApp
on:
  push:
    branches:
    - testing
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: Ubuntu-20.04
    timeout-minutes: 90  
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise will fail to push refs to dest repo

    - name: Run Testing Script
      run: |
          sudo ./run_tests.sh
